### ISSUE TITLE
BSOD on Windows 8.1x64 (6.3.9600.17415 IR5) 

### ISSUE THREAD

**Issue by assorted** [Mattiwatti/EfiGuard#24]
<img width="297" alt="bsod8 1" src="https://user-images.githubusercontent.com/6564333/111431350-bb7fbc00-870c-11eb-9a0b-08c5b7283fbd.png">
<img width="512" alt="bsod8 1_2" src="https://user-images.githubusercontent.com/6564333/111431502-ef5ae180-870c-11eb-9ae4-722396847f12.png">

**Comment by Mattiwatti** [comment]
Hi,

Can you try the latest release (v1.1.1) to see if it fixes the problem? I've had a look at this kernel revision and `KiVerifyScopesExecute` has a prologue that will throw off the old function backtracking algorithm and cause it to overshoot (backwards). I believe this should be fixed with f8ca8c0 though.

**Comment by assorted** [comment]
Thank you, I will.

**Comment by assorted** [comment]
Quite right, it was an outdated version.
