### ISSUE TITLE
Can't install the efi

### ISSUE THREAD

**Issue by Fraudly** [Mattiwatti/EfiGuard#68]
I tried to install efi, but it says it does not support legacy (non-uefi) even though I have "UEFI only" in CSM
![IMG_7159](https://user-images.githubusercontent.com/106556766/190864799-4ca4c5d1-805b-400b-99ea-172ae3390ec3.jpg)

**Comment by Mattiwatti** [comment]
From the device path being booted (`/USB(..),/HD(1,MBR,..)`) you can see that this is a legacy MBR drive (or possibly USB stick, whatever you are booting from). This is independent from the CSM or any other settings in the BIOS setup. A UEFI installation would show `/USB(..),/HD(1,GPT,..)` instead for a GPT disk.

Your BIOS is configured correctly, you simply need to partition the disk as GPT disk (a Google search should point you to some guides for how to do this). EfiGuard is working as intended in this scenario since it does not work with legacy (MBR/BIOS) installations of Windows like it says on the screen.

**Comment by Fraudly** [comment]
Hi again, haven't posted in a while, just forgot about it, but after a while I tried to run efi again, even bought a new flash drive and with rufus made the partition as GPT, but I didn't understand why the installation didn't
 go at all, there wasn't even any error at all.
![IMG_8100](https://github.com/Mattiwatti/EfiGuard/assets/106556766/e11afd01-770e-443f-8e34-4993862e4bce)
