### ISSUE TITLE
After booting from USB getting an error

### ISSUE THREAD

**Issue by evosite2** [Mattiwatti/EfiGuard#96]
error for efidsefix.exe -d

C:\Users\swilk\EfiGuard-v1.2.1>efidsefix.exe -d
Disabling DSE...
CI!g_CiOptions at 0xFFFFF80149259418.
Failure: NtSetSystemEnvironmentValueEx error C000000D
AdjustCiOptions failed: C000000D

efidsefix.exe -i

SystemBootEnvironmentInformation:
        - BootIdentifier: {11c4be38-4a63-11ed-a69a-d8bbc1524f32}
        - FirmwareType: UEFI
        - BootFlags: 0x0

SystemModuleInformation:
        - Kernel: ntoskrnl.exe (\SystemRoot\system32\ntoskrnl.exe)

SystemCodeIntegrityInformation:
        - IntegrityOptions: 0x2001

SystemKernelDebuggerInformation:
        - KernelDebuggerEnabled: 0
        - KernelDebuggerNotPresent: 1

SystemKernelDebuggerInformationEx:
        - DebuggerAllowed: 0
        - DebuggerEnabled: 0
        - DebuggerPresent: 0

SharedUserData->KdDebuggerEnabled: 0x00

SystemKernelDebuggerFlags: 0x00

SystemCodeIntegrityPolicyInformation:
        - Options: 0x40000000
        - HVCIOptions: 0x0000

**Comment by Mattiwatti** [comment]
The version of EfiGuard you're using is out of date (v1.2.1, current latest is v1.3). I'm mentioning this to address the original title (`KMODE_EXCEPTION_NOT_HANDLED`) as this was most likely caused by having HVCI enabled which v1.3 will now disable for you if needed.

Your updated issue (`EfiDSEFix` printing `C000000D`, meaning `STATUS_INVALID_PARAMETER`) also has an updated error description in v1.3, but what this basically comes down to is the DXE driver not being loaded, or else loaded incorrectly. EfiGuard itself does not return this status under any circumstance if it was loaded during boot.
